wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.4
feature_dropout:
  value: 0.1
l2_regularization:
  value: 2.308856018859458e-06
lr:
  value: 0.05007052274403501
output_regularization:
  value: 0.08331623781838475
