wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.2
feature_dropout:
  value: 0
l2_regularization:
  value: 1.838638720947227e-06
lr:
  value: 0.07765920581828127
output_regularization:
  value: 0.004002642714191088
