wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.4
feature_dropout:
  value: 0.1
l2_regularization:
  value: 3.394488186734224e-06
lr:
  value: 0.09083353763648136
output_regularization:
  value: 0.01008311166566623
