wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.1
feature_dropout:
  value: 0.05
l2_regularization:
  value: 5.587723022840879e-06
lr:
  value: 0.08046380250135636
output_regularization:
  value: 0.092507278721925
