wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.1
feature_dropout:
  value: 0.2
l2_regularization:
  value: 4.409001192636556e-06
lr:
  value: 0.08468525853177511
output_regularization:
  value: 0.09127930531687035
