wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.05
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.6759182283479935e-06
lr:
  value: 0.09884554434402316
output_regularization:
  value: 0.05797232111481527
