wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0.05
feature_dropout:
  value: 0
l2_regularization:
  value: 3.933500329458682e-06
lr:
  value: 0.012958846477951742
output_regularization:
  value: 0.015573894769963287
