wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 4.820815807934409e-06
lr:
  value: 0.0931726485360874
output_regularization:
  value: 0.04048406942494629
