wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 2.1694167649161743e-06
lr:
  value: 0.05436886292814644
output_regularization:
  value: 0.026811567255659023
