wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.7
feature_dropout:
  value: 0.1
l2_regularization:
  value: 7.184341252485085e-05
lr:
  value: 0.006101688690324015
output_regularization:
  value: 0.015868538198256805
