wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 1.774362712163386e-06
lr:
  value: 0.09186739500984777
output_regularization:
  value: 0.026566623872443147
