wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.1337830361510534e-06
lr:
  value: 0.07999717060412016
output_regularization:
  value: 0.06773259779062428
