wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.2
feature_dropout:
  value: 0.2
l2_regularization:
  value: 1.2735922956214826e-06
lr:
  value: 0.08234102366372281
output_regularization:
  value: 0.0874314952220591
