wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 1.4640076791162389e-06
lr:
  value: 0.0919654902038302
output_regularization:
  value: 0.03281951944416908
