wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0.1
feature_dropout:
  value: 0
l2_regularization:
  value: 2.9592907342786876e-05
lr:
  value: 0.016214679285639733
output_regularization:
  value: 0.003745610261496758
