wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.2
feature_dropout:
  value: 0.2
l2_regularization:
  value: 2.170218200873332e-06
lr:
  value: 0.07343037610490906
output_regularization:
  value: 0.04226385655087647
