wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.1
feature_dropout:
  value: 0.1
l2_regularization:
  value: 3.4095878142185938e-06
lr:
  value: 0.05479259908305873
output_regularization:
  value: 0.06539181710911131
