wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.1
feature_dropout:
  value: 0
l2_regularization:
  value: 2.135830684755986e-06
lr:
  value: 0.06701676496968467
output_regularization:
  value: 0.07670165487523566
