wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.7
feature_dropout:
  value: 0
l2_regularization:
  value: 1.4764269997439e-06
lr:
  value: 0.047130456224112306
output_regularization:
  value: 0.04580514567684916
