wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.1
feature_dropout:
  value: 0.05
l2_regularization:
  value: 4.00105257898722e-06
lr:
  value: 0.08403589745238396
output_regularization:
  value: 0.01587196685304584
