wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.6
feature_dropout:
  value: 0.05
l2_regularization:
  value: 6.5545294333562706e-06
lr:
  value: 0.001961779647846546
output_regularization:
  value: 0.03192988474433297
