wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0.005
dropout:
  value: 0.3
feature_dropout:
  value: 0.2
l2_regularization:
  value: 1.3106062059979566e-06
lr:
  value: 0.08743965846443369
output_regularization:
  value: 0.041699970826868
