wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.7
feature_dropout:
  value: 0
l2_regularization:
  value: 7.091344178308276e-05
lr:
  value: 0.008292707920207695
output_regularization:
  value: 0.002357635309121015
