wandb_version: 1

dropout:
  desc: null
  value: 0.3
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 1.0850647965064622e-06
lr:
  desc: null
  value: 0.039099471961308814
output_regularization:
  desc: null
  value: 0.004107009160043816
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688475242.593504
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
