wandb_version: 1

activation:
  desc: null
  value: exu
dropout:
  desc: null
  value: 0.8
feature_dropout:
  desc: null
  value: 0.2
l2_regularization:
  desc: null
  value: 1.0298041141006931e-06
lr:
  desc: null
  value: 0.04916967822680593
output_regularization:
  desc: null
  value: 0.0031732397183573124
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688463728.664243
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
