wandb_version: 1

activation:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.05
feature_dropout:
  desc: null
  value: 0.05
l2_regularization:
  desc: null
  value: 3.7146883841632584e-06
lr:
  desc: null
  value: 0.043222420692878745
output_regularization:
  desc: null
  value: 0.04146568023780473
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688464204.469204
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
