wandb_version: 1

activation:
  desc: null
  value: relu
decay_rate:
  desc: null
  value: 0.05
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 7.389669269065833e-05
lr:
  desc: null
  value: 0.0020205279113850727
output_regularization:
  desc: null
  value: 0.0036039597255642505
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688378124.845113
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
