wandb_version: 1

activation_cls:
  desc: null
  value: elu
batch_size:
  desc: null
  value: 128
decay_rate:
  desc: null
  value: 0.001089876642083436
lr:
  desc: null
  value: 0.02650704005920677
num_epochs:
  desc: null
  value: 87
num_layers:
  desc: null
  value: 4
num_units:
  desc: null
  value: 168
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705662206.330219
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
