wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0.1
feature_dropout:
  value: 0
l2_regularization:
  value: 7.942109647612942e-05
lr:
  value: 0.004005721156316136
output_regularization:
  value: 0.004723929422998972
