wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 2.6180838953919275e-05
lr:
  value: 0.00939741891083648
output_regularization:
  value: 0.0013500624867181584
