wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 2.7304029245080863e-05
lr:
  value: 0.0026940252774552524
output_regularization:
  value: 0.003726511534324525
