wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0.2
feature_dropout:
  value: 0.2
l2_regularization:
  value: 1.1136480915121408e-06
lr:
  value: 0.00854018760591977
output_regularization:
  value: 0.02478522760345988
