wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.7
feature_dropout:
  value: 0.05
l2_regularization:
  value: 9.19617271281209e-06
lr:
  value: 0.002118547943773626
output_regularization:
  value: 0.002801114052658371
