wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.2
feature_dropout:
  value: 0.2
l2_regularization:
  value: 2.882613873746632e-05
lr:
  value: 0.0362294095179164
output_regularization:
  value: 0.006370129275785536
