wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.5
feature_dropout:
  value: 0.2
l2_regularization:
  value: 6.70319013005633e-05
lr:
  value: 0.05501714946120969
output_regularization:
  value: 0.00567771259217102
