wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.2
feature_dropout:
  value: 0.2
l2_regularization:
  value: 5.597473643027439e-05
lr:
  value: 0.07040957717041726
output_regularization:
  value: 0.01569648533802771
