wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.3
feature_dropout:
  value: 0.1
l2_regularization:
  value: 2.831913976794265e-06
lr:
  value: 0.04158502005729554
output_regularization:
  value: 0.07974480487585558
