wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.1
feature_dropout:
  value: 0.2
l2_regularization:
  value: 8.15709998810933e-05
lr:
  value: 0.0592021861853924
output_regularization:
  value: 0.002219807571014961
