wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.2
l2_regularization:
  value: 1.649990511041019e-05
lr:
  value: 0.07907550345043653
output_regularization:
  value: 0.006039204702493109
