wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.05
feature_dropout:
  value: 0.05
l2_regularization:
  value: 6.804955449115274e-05
lr:
  value: 0.0012817382196561766
output_regularization:
  value: 0.0699257869069201
