wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0.3
feature_dropout:
  value: 0.2
l2_regularization:
  value: 3.51768479723218e-05
lr:
  value: 0.02755843935239935
output_regularization:
  value: 0.002433902515263066
