wandb_version: 1

dropout:
  desc: null
  value: 0.6
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 2.498617899840999e-06
lr:
  desc: null
  value: 0.010269989006748567
output_regularization:
  desc: null
  value: 0.00919414927259395
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688476291.586156
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
