wandb_version: 1

activation_cls:
  desc: null
  value: elu
batch_size:
  desc: null
  value: 256
decay_rate:
  desc: null
  value: 0.013314216238409088
lr:
  desc: null
  value: 0.0007783988155753517
num_epochs:
  desc: null
  value: 65
num_layers:
  desc: null
  value: 3
num_units:
  desc: null
  value: 263
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705673050.710772
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
