wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.2
l2_regularization:
  value: 7.427878366075509e-05
lr:
  value: 0.009126485469998636
output_regularization:
  value: 0.004928737283018773
