wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.2
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 6.365622499998551e-05
lr:
  desc: null
  value: 0.0010832322250838376
output_regularization:
  desc: null
  value: 0.004359721425757243
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688501846.360348
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
