wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0.05
dropout:
  desc: null
  value: 0.3
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 1.1665937264813147e-06
lr:
  desc: null
  value: 0.03849993142473646
output_regularization:
  desc: null
  value: 0.06933535621206659
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688372291.701051
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
