wandb_version: 1

activation_cls:
  desc: null
  value: elu
batch_size:
  desc: null
  value: 256
decay_rate:
  desc: null
  value: 1.018126702806352e-05
lr:
  desc: null
  value: 0.0008040934924928585
num_epochs:
  desc: null
  value: 51
num_layers:
  desc: null
  value: 2
num_units:
  desc: null
  value: 270
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705662484.093107
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
