wandb_version: 1

regression:
  desc: null
  value: true
use_dnn:
  desc: null
  value: false
num_epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 64
shuffle:
  desc: null
  value: true
early_stopping_patience:
  desc: null
  value: 50
decay_rate:
  desc: null
  value: 0.005
logdir:
  desc: null
  value: output
wandb:
  desc: null
  value: false
log_loss_frequency:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
l2_regularization:
  desc: null
  value: 0
output_regularization:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0
num_basis_functions:
  desc: null
  value: 64
hidden_sizes:
  desc: null
  value:
  - 64
  - 32
activation:
  desc: null
  value: exu
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688290278.210604
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
