wandb_version: 1

activation:
  desc: null
  value: exu
dropout:
  desc: null
  value: 0.8
feature_dropout:
  desc: null
  value: 0.05
l2_regularization:
  desc: null
  value: 1.5129549741632056e-05
lr:
  desc: null
  value: 0.0017346260403418908
output_regularization:
  desc: null
  value: 0.005560163364806886
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688464288.787253
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
