wandb_version: 1

dropout:
  desc: null
  value: 0.8
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 2.012203257488411e-05
lr:
  desc: null
  value: 0.013200473255195909
output_regularization:
  desc: null
  value: 0.002489292201114569
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688474815.630293
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
