wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0.005
dropout:
  desc: null
  value: 0.7
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 1.9922178081206502e-05
lr:
  desc: null
  value: 0.017886952591896606
output_regularization:
  desc: null
  value: 0.03967904749349063
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688829322.064522
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
