wandb_version: 1

activation:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 2.259752533498675e-06
lr:
  desc: null
  value: 0.0020333450631569265
output_regularization:
  desc: null
  value: 0.06017745499149846
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688465096.497675
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
