wandb_version: 1

activation:
  desc: null
  value: exu
dropout:
  desc: null
  value: 0.7
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 3.0282043148158632e-06
lr:
  desc: null
  value: 0.042779752815866
output_regularization:
  desc: null
  value: 0.001386799259354689
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688463523.025709
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
