wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 8.332496807476971e-05
lr:
  value: 0.07912268668322563
output_regularization:
  value: 0.01826065633262493
