wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.1
feature_dropout:
  value: 0.05
l2_regularization:
  value: 9.005307242002468e-05
lr:
  value: 0.04226344080079429
output_regularization:
  value: 0.004193336414554139
