wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 5.49002826198936e-05
lr:
  value: 0.0475633723009358
output_regularization:
  value: 0.003208637280065763
