wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 5.1012515890765984e-05
lr:
  value: 0.01265598887315168
output_regularization:
  value: 0.01446140416449084
