wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 4.462958942618339e-05
lr:
  value: 0.00881077718950128
output_regularization:
  value: 0.007118820519358556
