wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.2
l2_regularization:
  value: 8.98718645616825e-05
lr:
  value: 0.007590111831986884
output_regularization:
  value: 0.008292811268771065
