wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 8.989275580043283e-05
lr:
  value: 0.0218678440649494
output_regularization:
  value: 0.028711802782602956
