wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 8.927579235422821e-05
lr:
  value: 0.026987616280215065
output_regularization:
  value: 0.007509128289293248
