wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 6.249868688730754e-05
lr:
  value: 0.015622559321175074
output_regularization:
  value: 0.03053161937481296
