wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 6.349117667426936e-05
lr:
  value: 0.02542796301172503
output_regularization:
  value: 0.02004959034792883
