wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 3.118906221322762e-05
lr:
  value: 0.024565753365556144
output_regularization:
  value: 0.006010800249054458
