wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 5.206475201815554e-05
lr:
  value: 0.04471831264980242
output_regularization:
  value: 0.002305211150818576
