wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 7.642986426801762e-05
lr:
  value: 0.05285958212756428
output_regularization:
  value: 0.007239726207097511
