wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 3.53667352440474e-05
lr:
  value: 0.01060409942436154
output_regularization:
  value: 0.0059835319404257445
