wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 8.450478309459362e-05
lr:
  value: 0.0391070422977954
output_regularization:
  value: 0.011291150825109264
