wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 2.928387447440134e-05
lr:
  value: 0.0772168558098641
output_regularization:
  value: 0.003850158089665872
