wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0.2
l2_regularization:
  value: 3.889654447723514e-05
lr:
  value: 0.07004525733986315
output_regularization:
  value: 0.013223848892953242
