wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 4.631609591678196e-05
lr:
  value: 0.054396143263619814
output_regularization:
  value: 0.010470977923804808
