wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.005
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 2.852727141682212e-05
lr:
  value: 0.03785143188626482
output_regularization:
  value: 0.013624434404372507
