wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.1
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 2.9592907342786876e-05
lr:
  desc: null
  value: 0.016214679285639733
output_regularization:
  desc: null
  value: 0.003745610261496758
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688829492.535803
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
