device: 'cpu'
dataset: 
    name: 'concurvity'
model: 
    name: 'nam'

num_layers: 2
num_units: 460
activation: True
activation_cls: 'elu'

likelihood: 'regression'
num_epochs: 73
batch_size: 256
lr: 0.002115857765136438
decay_rate: 0.0000932596605843508

num_ensemble: 5

prior_sigma_noise: 0
prior_prec_init: 1
lr_hyp: 0.1
n_epochs_burnin: 50
n_hypersteps: 30
marglik_frequency: 100

early_stopping_patience: 10 
early_stopping_delta: 0


l2_regularization: 0
dropout: 0
feature_dropout: 0

concurvity_regularization: 0
hsic_regularization: 0
l1_regularization: 0
perctile_epochs_burnin: 0.05


wandb: 
    use: true
    entity: 'xinyu-zhang'
    project: 'kernel-based-concurvity-regularization-in-NAMs'
    
log_loss_frequency: 10
 
