wandb_version: 1

activation:
  desc: null
  value: relu
decay_rate:
  desc: null
  value: 0.005
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0.05
l2_regularization:
  desc: null
  value: 1.4640076791162389e-06
lr:
  desc: null
  value: 0.0919654902038302
output_regularization:
  desc: null
  value: 0.03281951944416908
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688827713.829728
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
