wandb_version: 1

activation_cls:
  desc: null
  value: gelu
decay_rate:
  desc: null
  value: 8.852095723038326e-06
lr:
  desc: null
  value: 0.0036836411916164537
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705620191.75075
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
