wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 512
decay_rate:
  value: 0.2967636914660497
lr:
  value: 0.00010165470918048022
num_epochs:
  value: 86
num_layers:
  value: 6
num_units:
  value: 361
