wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 256
decay_rate:
  value: 0.043451060632055685
lr:
  value: 0.0018128855161443707
num_epochs:
  value: 75
num_layers:
  value: 6
num_units:
  value: 200
