wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 256
decay_rate:
  value: 0.0960745286122161
lr:
  value: 0.0003406427790991
num_epochs:
  value: 66
num_layers:
  value: 2
num_units:
  value: 64
