wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 256
decay_rate:
  value: 1.018126702806352e-05
lr:
  value: 0.0008040934924928585
num_epochs:
  value: 51
num_layers:
  value: 2
num_units:
  value: 270
