wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 512
decay_rate:
  value: 4.7923224945439413e-05
lr:
  value: 0.001405182266001635
num_epochs:
  value: 84
num_layers:
  value: 4
num_units:
  value: 371
