wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 256
decay_rate:
  value: 0.0354227320338121
lr:
  value: 0.010991286723847828
num_epochs:
  value: 50
num_layers:
  value: 1
num_units:
  value: 40
