wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 512
decay_rate:
  value: 0.14487346624518063
lr:
  value: 0.004504405747157503
num_epochs:
  value: 41
num_layers:
  value: 2
num_units:
  value: 140
