wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 256
decay_rate:
  value: 0.07181233014118532
lr:
  value: 0.006615812754365009
num_epochs:
  value: 56
num_layers:
  value: 6
num_units:
  value: 319
