wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 128
decay_rate:
  value: 0.0027415437006006395
lr:
  value: 0.03401989077745426
num_epochs:
  value: 69
num_layers:
  value: 1
num_units:
  value: 363
