wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 256
decay_rate:
  value: 0.13216943516946847
lr:
  value: 0.022741325954022916
num_epochs:
  value: 97
num_layers:
  value: 5
num_units:
  value: 301
