wandb_version: 1

activation_cls:
  value: relu
batch_size:
  value: 512
decay_rate:
  value: 4.229236393053058e-06
lr:
  value: 0.06306999438031802
num_epochs:
  value: 56
num_layers:
  value: 5
num_units:
  value: 134
