wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 256
decay_rate:
  value: 7.579790730726673e-05
lr:
  value: 0.00012937930472723332
num_epochs:
  value: 92
num_layers:
  value: 2
num_units:
  value: 444
