wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 512
decay_rate:
  value: 0.038430873177795706
lr:
  value: 0.009161472019933604
num_epochs:
  value: 41
num_layers:
  value: 1
num_units:
  value: 365
