wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 256
decay_rate:
  value: 0.13504183701432715
lr:
  value: 0.03426447886971344
num_epochs:
  value: 85
num_layers:
  value: 4
num_units:
  value: 471
