wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 128
decay_rate:
  value: 9.380295028262256e-05
lr:
  value: 0.0007998413068490651
num_epochs:
  value: 40
num_layers:
  value: 2
num_units:
  value: 479
