wandb_version: 1

activation_cls:
  value: gelu
batch_size:
  value: 128
decay_rate:
  value: 0.0002616233289283635
lr:
  value: 0.007642003030301342
num_epochs:
  value: 74
num_layers:
  value: 5
num_units:
  value: 60
