wandb_version: 1

activation_cls:
  value: relu
batch_size:
  value: 128
decay_rate:
  value: 0.000113634773455193
lr:
  value: 0.0017421624888924877
num_epochs:
  value: 43
num_layers:
  value: 1
num_units:
  value: 483
