wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 256
decay_rate:
  value: 0.013314216238409088
lr:
  value: 0.0007783988155753517
num_epochs:
  value: 65
num_layers:
  value: 3
num_units:
  value: 263
