wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 128
decay_rate:
  value: 0.003818272439224988
lr:
  value: 0.004391189735971752
num_epochs:
  value: 60
num_layers:
  value: 2
num_units:
  value: 275
