wandb_version: 1

activation_cls:
  value: relu
batch_size:
  value: 128
decay_rate:
  value: 1.9699515081925433e-06
lr:
  value: 0.0018505104442000223
num_epochs:
  value: 57
num_layers:
  value: 2
num_units:
  value: 466
