wandb_version: 1

activation_cls:
  value: elu
batch_size:
  value: 256
decay_rate:
  value: 9.32596605843508e-05
lr:
  value: 0.002115857765136438
num_epochs:
  value: 73
num_layers:
  value: 2
num_units:
  value: 460
