wandb_version: 1

activation:
  desc: null
  value: relu
decay_rate:
  desc: null
  value: 0.005
dropout:
  desc: null
  value: 0.8
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 1.513991289333151e-06
lr:
  desc: null
  value: 0.05807606658709341
output_regularization:
  desc: null
  value: 0.018934894193692608
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688829251.182313
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
