wandb_version: 1

activation_cls:
  desc: null
  value: elu
decay_rate:
  desc: null
  value: 4.860057012323132e-06
lr:
  desc: null
  value: 0.029402553237843004
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705620036.90258
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
