wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0.9
feature_dropout:
  value: 0.05
l2_regularization:
  value: 3.910823166017795e-05
lr:
  value: 0.005348329730310528
output_regularization:
  value: 0.06356358094409578
