wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.2170830751450228e-05
lr:
  value: 0.07846790405150324
output_regularization:
  value: 0.020539095124272183
