wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 5.220391210407674e-05
lr:
  value: 0.09994908853204948
output_regularization:
  value: 0.0021625451960199525
