wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 5.954968476402653e-05
lr:
  value: 0.04499496082984274
output_regularization:
  value: 0.008484928723000293
