wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.5147025320087202e-05
lr:
  value: 0.0838591108987599
output_regularization:
  value: 0.009392195649949612
