wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.5570526679999562e-05
lr:
  value: 0.06728039580858072
output_regularization:
  value: 0.01067773942553927
