wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 9.631242673428531e-05
lr:
  value: 0.08880421463604259
output_regularization:
  value: 0.028388205000563188
