wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 3.032009454078034e-05
lr:
  value: 0.004872259506250532
output_regularization:
  value: 0.004799913627543389
