wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0.2
feature_dropout:
  value: 0
l2_regularization:
  value: 9.346583546299982e-06
lr:
  value: 0.0019169664554796611
output_regularization:
  value: 0.08126505390545091
