wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 5.768852190658149e-05
lr:
  value: 0.005144931709490901
output_regularization:
  value: 0.008313595983639724
