wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 6.481377457246216e-06
lr:
  value: 0.07088587088134235
output_regularization:
  value: 0.002868215265921762
