wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 8.574258102729356e-06
lr:
  value: 0.03637724488381857
output_regularization:
  value: 0.00579536480441228
