wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 3.629988295914133e-06
lr:
  value: 0.08243066770409539
output_regularization:
  value: 0.004775530938028512
