wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 2.8848947315475062e-05
lr:
  value: 0.04024286806022449
output_regularization:
  value: 0.002865907426141481
