wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 2.37472169036572e-05
lr:
  value: 0.05926558574644572
output_regularization:
  value: 0.012105608625429353
