wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.619310401236387e-05
lr:
  value: 0.01964241373446391
output_regularization:
  value: 0.007174897430418582
