wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 6.090578153712378e-05
lr:
  value: 0.028882832402566956
output_regularization:
  value: 0.003083709669385248
