wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0.05
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 9.01769597017014e-06
lr:
  value: 0.005433021921088721
output_regularization:
  value: 0.0272791813776933
