wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0.1
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.8096438516234905e-05
lr:
  value: 0.008265164878622569
output_regularization:
  value: 0.016718876627334303
