wandb_version: 1

activation:
  desc: null
  value: exu
dropout:
  desc: null
  value: 0.3
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 8.853430883492457e-05
lr:
  desc: null
  value: 0.07933218659743661
output_regularization:
  desc: null
  value: 0.0022641317158540895
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688463564.265409
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
