wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0.005
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0.05
l2_regularization:
  desc: null
  value: 2.1075022644350635e-05
lr:
  desc: null
  value: 0.0057319068636101644
output_regularization:
  desc: null
  value: 0.002885875668203509
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688501809.286357
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
