wandb_version: 1

activation_cls:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 128
decay_rate:
  desc: null
  value: 0.00017009107915246413
lr:
  desc: null
  value: 0.014286254696289056
num_epochs:
  desc: null
  value: 96
num_layers:
  desc: null
  value: 1
num_units:
  desc: null
  value: 87
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705669408.613244
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
