wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0.2
l2_regularization:
  desc: null
  value: 6.93491127263477e-05
lr:
  desc: null
  value: 0.005021647654321494
output_regularization:
  desc: null
  value: 0.003491905069999896
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688500376.748091
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
