wandb_version: 1

dropout:
  desc: null
  value: 0.3
feature_dropout:
  desc: null
  value: 0.2
l2_regularization:
  desc: null
  value: 1.1852442598877247e-05
lr:
  desc: null
  value: 0.09055932479514392
output_regularization:
  desc: null
  value: 0.07040417068861195
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688476875.070393
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
