wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.05
l2_regularization:
  value: 5.898578274175914e-05
lr:
  value: 0.009882732998729646
output_regularization:
  value: 0.005178300627637676
