wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688289445.480155
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
magic:
  desc: null
  value:
    enable: true
f:
  desc: null
  value: /home/zhangx18/.local/share/jupyter/runtime/kernel-01fc13f9-d2e7-49f1-a937-636eab7f99c4.json
