wandb_version: 1

activation_cls:
  desc: null
  value: gelu
batch_size:
  desc: null
  value: 128
decay_rate:
  desc: null
  value: 2.462322292305256e-06
lr:
  desc: null
  value: 0.009154464405433764
num_epochs:
  desc: null
  value: 60
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705622982.277455
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 50
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
