wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0
l2_regularization:
  value: 7.226102479960298e-05
lr:
  value: 0.0013660423282269387
output_regularization:
  value: 0.005416080971585659
