wandb_version: 1

activation:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.7
feature_dropout:
  desc: null
  value: 0.2
l2_regularization:
  desc: null
  value: 1.1717495165198003e-05
lr:
  desc: null
  value: 0.007014308219547807
output_regularization:
  desc: null
  value: 0.009509492238307255
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688463480.719484
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
