wandb_version: 1

dropout:
  desc: null
  value: 0.2
feature_dropout:
  desc: null
  value: 0.2
l2_regularization:
  desc: null
  value: 7.519854338527962e-05
lr:
  desc: null
  value: 0.010100585647603992
output_regularization:
  desc: null
  value: 0.08024632536243553
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688476240.165486
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
