wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 2.3913914804708185e-05
lr:
  value: 0.03273982805033809
output_regularization:
  value: 0.004262218603199714
