wandb_version: 1

activation:
  value: relu
decay_rate:
  value: 0.05
dropout:
  value: 0.7
feature_dropout:
  value: 0
l2_regularization:
  value: 9.200746382483235e-06
lr:
  value: 0.029955310826127676
output_regularization:
  value: 0.004043117499131841
