wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0.05
dropout:
  value: 0.3
feature_dropout:
  value: 0
l2_regularization:
  value: 1.1665937264813147e-06
lr:
  value: 0.03849993142473646
output_regularization:
  value: 0.06933535621206659
