wandb_version: 1

activation:
  value: exu
decay_rate:
  value: 0
dropout:
  value: 0
feature_dropout:
  value: 0.1
l2_regularization:
  value: 1.3401651197076838e-05
lr:
  value: 0.0014082133924083649
output_regularization:
  value: 0.0404016387509033
