wandb_version: 1

activation:
  desc: null
  value: relu
decay_rate:
  desc: null
  value: 0.005
dropout:
  desc: null
  value: 0
feature_dropout:
  desc: null
  value: 0.05
l2_regularization:
  desc: null
  value: 7.064207707034379e-05
lr:
  desc: null
  value: 0.022926767577603677
output_regularization:
  desc: null
  value: 0.013390099725332163
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688843882.804513
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
