wandb_version: 1

activation:
  desc: null
  value: relu
decay_rate:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.05
feature_dropout:
  desc: null
  value: 0.1
l2_regularization:
  desc: null
  value: 1.6759182283479935e-06
lr:
  desc: null
  value: 0.09884554434402316
output_regularization:
  desc: null
  value: 0.05797232111481527
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688827843.400105
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
