wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0.05
dropout:
  desc: null
  value: 0.05
feature_dropout:
  desc: null
  value: 0
l2_regularization:
  desc: null
  value: 1.7778146181572907e-05
lr:
  desc: null
  value: 0.0033975984475730797
output_regularization:
  desc: null
  value: 0.005284066973300202
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688379615.898287
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
