wandb_version: 1

activation:
  desc: null
  value: exu
decay_rate:
  desc: null
  value: 0.005
dropout:
  desc: null
  value: 0.2
feature_dropout:
  desc: null
  value: 0.05
l2_regularization:
  desc: null
  value: 1.2760628808631929e-05
lr:
  desc: null
  value: 0.001397258353876662
output_regularization:
  desc: null
  value: 0.0052123418478128075
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688500762.762777
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 5
